### ISSUE TITLE
Some materials on Genetic Programming

### ISSUE THREAD

**Issue by hengzhe-zhang** [Evolutionary-Intelligence/EC-A-Modern-Perspective#1]
Here are some reading materials on genetic programming. Feel free to read them if you find them useful.

https://github.com/hengzhe-zhang/awesome-genetic-programming

**Comment by Evolutionary-Intelligence** [comment]
Thanks for your attention. However, one important GP paper published in **Science** is missed in your link. It is better to include it, depending on only our personal viewpoint.

**Comment by Evolutionary-Intelligence** [comment]
In addition, it is better to include the **Nature** book review of Koza's classical book (just a recommendation).

**Comment by Evolutionary-Intelligence** [comment]
https://people.idsia.ch/~juergen/genetic-programming-1987.html appears to be not missed.

**Comment by hengzhe-zhang** [comment]
Thanks. I have added a sub-list to record papers that are more than five years old.

![image](https://github.com/Evolutionary-Intelligence/EC-A-Modern-Perspective/assets/18747119/8a2de39a-0a41-4a50-bb60-1884c3461ff6)
